version: '3'
services:
  app:
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    build:
      ./app
    restart: always
    container_name: app
    volumes:
    - ./app/adminServer:/codigo
    - ./app/logs:/codigo/bitacora
    - ../monitorPS2020/nginx/certs/172.16.10.17_cert.crt:/tmp/srv_monitoreo_cert.crt:ro
    depends_on:
      - bd
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "750M"

  bd:
    image: mariadb:10.2.21
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
    - ../data_mysql_appproy2020:/var/lib/mysql


  nginx:
    image: nginx
    restart: always
    ports:
      - 10000:80 #se redirige al 80 de nginx
      - 9807:443
    volumes:
      - ./nginx/cnginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./app/adminServer/static:/static # se mapea a static del proyecto
      - ./nginx/certs:/tmp
    depends_on:
      - app
