version: '3'
services:
  app:
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    build:
      ./app
    restart: always
    container_name: app
    volumes:
    - ./app/adminServer:/codigo
    - ./app/logs:/codigo/bitacora
    depends_on:
      - bd

  bd:
    image: mariadb:10.2.21
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
    - ./data:/var/lib/mysql


  nginx:
    image: nginx
    restart: always
    ports:
      - 8000:80 #se redirige al 80 de nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./app/adminServer/static:/static # se mapea a static del proyecto
    depends_on:
      - app
