# Generated by Django 2.0.3 on 2020-01-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servidores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc_srv', models.CharField(max_length=32)),
                ('ip_srv', models.GenericIPAddressField()),
                ('status', models.CharField(max_length=1)),
                ('fh_srv', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usr', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=32)),
                ('correo', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
