# Generated by Django 2.0.3 on 2020-01-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_proyectoDW', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidores',
            name='fh_srv',
            field=models.DateTimeField(),
        ),
    ]
