# Generated by Django 3.0.5 on 2020-07-10 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usr', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Usuario')),
                ('pwd', models.CharField(max_length=80, verbose_name='Contraseña')),
                ('nombres', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellidos', models.CharField(blank=True, max_length=20, verbose_name='Apellido')),
                ('correo', models.EmailField(blank=True, max_length=32, null=True)),
                ('numero', models.CharField(blank=True, max_length=12, null=True)),
                ('chat_id', models.CharField(blank=True, default=0, max_length=15, null=True)),
                ('token', models.CharField(default=0, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Tglobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=0, max_length=16, verbose_name='Token Administrador global')),
                ('chat_id', models.CharField(blank=True, default=0, max_length=15, null=True, verbose_name='Chat Id Administrador global')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc_srv', models.CharField(max_length=16)),
                ('ip_srv', models.CharField(max_length=12)),
                ('puerto', models.IntegerField()),
                ('estado', models.BooleanField(default=True, verbose_name='Activo/Inactivo')),
                ('usr_srv', models.CharField(default=' ', max_length=25, verbose_name='Usuario servidor')),
                ('pwd_srv', models.CharField(default='0', max_length=50, verbose_name='Contraseña Servidor')),
                ('puerto_tty', models.CharField(default='0', max_length=5, verbose_name='Puerto terminal')),
                ('llave', models.CharField(default='0', max_length=50)),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.Usuario')),
            ],
        ),
    ]
