# Generated by Django 3.0.5 on 2020-05-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='chat_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='puerto',
            field=models.IntegerField(),
        ),
    ]
