# Generated by Django 3.0.5 on 2020-05-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0002_auto_20200501_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
