# Generated by Django 3.0.5 on 2020-05-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0003_auto_20200501_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='token',
            field=models.CharField(default=0, max_length=16),
        ),
    ]
