# Generated by Django 3.0.5 on 2020-05-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0004_auto_20200504_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(blank=True, max_length=20, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='chat_id',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usr',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Usuario'),
        ),
    ]
