# Generated by Django 3.0.5 on 2020-05-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0005_auto_20200504_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pwd',
            field=models.CharField(max_length=42, verbose_name='Contraseña'),
        ),
    ]
