# Generated by Django 3.0.5 on 2020-06-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0007_servidor_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='pwd_srv',
            field=models.CharField(default='0', max_length=50, verbose_name='Contraseña Servidor'),
        ),
    ]
