# Generated by Django 3.0.5 on 2020-06-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0008_servidor_pwd_srv'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='llave',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
