# Generated by Django 3.0.5 on 2020-06-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0009_servidor_llave'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='usr_srv',
            field=models.CharField(default=' ', max_length=25, verbose_name='Usuario servidor'),
        ),
    ]
