# Generated by Django 3.0.5 on 2020-06-27 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appWeb', '0011_auto_20200627_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tglobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=0, max_length=16, verbose_name='Token Administrador global')),
                ('chat_id', models.CharField(blank=True, default=0, max_length=15, null=True, verbose_name='Chat Id Administrador global')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
