# Generated by Django 3.0.5 on 2020-06-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0012_tglobal'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='puerto_tty',
            field=models.CharField(default='0', max_length=5, verbose_name='Puerto terminal'),
        ),
    ]
